default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medservice_development

test:
  <<: *default
  database: medservice_test

production:
  <<: *default
  database: medservice_production
  username: medservice
  password: <%= ENV["MEDSERVICE_DATABASE_PASSWORD"] %>
